# permissions for end users to edit networktraces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networktraces-editor-role
rules:
- apiGroups:
  - k8s-debugger.shuanglu.io
  resources:
  - networktraces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-debugger.shuanglu.io
  resources:
  - networktraces/status
  verbs:
  - get
