# permissions for end users to view networktraces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networktraces-viewer-role
rules:
- apiGroups:
  - k8s-debugger.shuanglu.io
  resources:
  - networktraces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-debugger.shuanglu.io
  resources:
  - networktraces/status
  verbs:
  - get
